spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  profiles:
    default: dev
  kafka:
    topic: chat-notifications
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    websocket:
      topic-base-path: /topic
      message-path: ${spring.websocket.topic-base-path}/message
server:
  port: 8080
#kafka:
#  enabled: true
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-app?useSSL=false&serverTimezone=UTC
    username: denysmatsenko
    password: 00zomifi
  kafka:
    bootstrap-servers: localhost:29092

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/chat-app?useSSL=false&serverTimezone=UTC
    username: denysmatsenko
    password: 00zomifi
  kafka:
    bootstrap-servers: broker:9092
kafka:
  enabled: true
